name: capturefacturas
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # librerias usadas por jesus
  firebase_core: ^0.3.4
  firebase_storage: ^2.1.0+1
  image_picker: ^0.3.0



  # librerias usadas por cesar
  firebase_auth: ^0.8.4
  flutter_auth_buttons: ^0.5.0
  google_sign_in: ^4.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true